# Generated by Django 2.1.1 on 2018-10-13 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20181010_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 9, 35, 41, 684169), verbose_name='订单创建时间'),
        ),
    ]
